// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5H9BpTZo3d1OoZXb00ZPwttM_IlUwfis',
    appId: '1:604031766306:web:29a807f87ace691325df7b',
    messagingSenderId: '604031766306',
    projectId: 'fir-flutter-alura',
    authDomain: 'fir-flutter-alura.firebaseapp.com',
    storageBucket: 'fir-flutter-alura.appspot.com',
    measurementId: 'G-T6V4BFT7W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkplIYeJMy4AAxbPDxA3Rb7_g6rVG4J84',
    appId: '1:604031766306:android:8519233630cc59c525df7b',
    messagingSenderId: '604031766306',
    projectId: 'fir-flutter-alura',
    storageBucket: 'fir-flutter-alura.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt0UeJrTSw7zs-d5VSk_N2RJMCbWyKaNE',
    appId: '1:604031766306:ios:e5010250390ba83c25df7b',
    messagingSenderId: '604031766306',
    projectId: 'fir-flutter-alura',
    storageBucket: 'fir-flutter-alura.appspot.com',
    iosClientId: '604031766306-6hf3q5d1rkf8iavri9dh9k848vfgougr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt0UeJrTSw7zs-d5VSk_N2RJMCbWyKaNE',
    appId: '1:604031766306:ios:e5010250390ba83c25df7b',
    messagingSenderId: '604031766306',
    projectId: 'fir-flutter-alura',
    storageBucket: 'fir-flutter-alura.appspot.com',
    iosClientId: '604031766306-6hf3q5d1rkf8iavri9dh9k848vfgougr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );
}
